### ISSUE TITLE
Inline assembly `byte` instruction doesn't work

### ISSUE THREAD

**Issue by samczsun** [ethereumjs/ethereumjs-vm#298] opened 2018-04-28 01:52 UTC
I have a simple contract which will extract an `uint8` from an `uint256`:

```
pragma solidity 0.4.23;

contract Test {
    function getByte(uint from, uint index) public pure returns (uint8 result) {
        assembly {
            result := byte(index, from)
        }
    }
}
```

Upon deployment to a chain, the function works as expected. Passing in `"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0"` results in `255`.

However, no matter the params, the JavaScript VM always returns `0`.

**Comment by holgerd77** [comment] 2018-04-28 04:07
Does this happen with the latest v2.3.5 release?

**Comment by axic** [comment] 2018-04-30 10:47
Duplicate of https://github.com/ethereum/remix/issues/783

Will be fixed in the next Remix release.

**Closed by axic** 2018-04-30 10:47 UTC
