### ISSUE TITLE
If `_addToBalance` is called and the result exceeds the MAX_INTEGER an error is thrown that isn't handled properly by the VM

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-vm#672] opened 2020-02-28 21:12 UTC
The Error returned by the EVM is `Returned error: Cannot get state root with uncommitted checkpoints`, however, the actual exception is `Error:Value overflow`, but this exception seems to be overshadowed by a checkpoint/revert bug.

The related truffle issue: https://github.com/trufflesuite/truffle/issues/2811

In this issue's case, the problem stems from the fact that ganache-core _currently_ permits starting an account with a balance greater than ethereumjs-util's `MAX_NUMBER`; we just write the balance directly to the trie upon initialization.

I can add in an arbitrary value check to ganache-core to disallow large starting balances, however, the `checkpoints` issue could still occur if the user seeds an account with an amount approaching `MAX_NUMBER`, then transfers enough additional value into it.

The `Value overflow` exception is thrown here
https://github.com/ethereumjs/ethereumjs-vm/blob/e2c191b1c93e71f832413bb904f4db521208ebac/packages/vm/lib/evm/evm.ts#L386

I managed to capture the following stack trace from within the compiled version of the CALL opcode while running a very large transfer from within a contract `ganache-core`:

```
Error: Value overflow
    at EVM.<anonymous> (/home/david/work/ganache-core/node_modules/ethereumjs-vm/lib/evm/evm.ts:385:13)
    at step (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:43:23)
    at Object.next (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:24:53)
    at /home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:14:12)
    at EVM._addToBalance (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:410:16)
    at EVM.<anonymous> (/home/david/work/ganache-core/node_modules/ethereumjs-vm/lib/evm/evm.ts:155:18)
    at step (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:43:23)
    at Object.next (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:24:53)
    at fulfilled (/home/david/work/ganache-core/node_modules/ethereumjs-vm/dist/evm/evm.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cgewecke** [comment] 2020-03-04 05:20
@davidmurdoch Thanks for finding this and for providing such a clear description. Have reproduced and can see source of the problem, will open a PR fixing shortly...

**Comment by jochem-brouwer** [comment] 2020-06-29 17:47
I think this one can be closed? @cgewecke

**Comment by cgewecke** [comment] 2020-06-30 15:31
Ah thanks @jochem-brouwer! forgot about this. 

I am not certain this  made it into `4.2.0`. It looks like it's part of the V5 milestone now.  

Are we closing issues when a fix is merged or when it's published?

**Comment by holgerd77** [comment] 2020-07-01 20:32
@cgewecke actually on EthereumJS we have no clear policy here, I think I've always closed issues from the time on a fix was merged. We might want to change here - not sure - for now I will close here as well, also since the targeted release is mentioned here in the lasts comments.

**Closed by holgerd77** 2020-07-01 20:32 UTC
Labels: package: vm
