### ISSUE TITLE
`allowUnlimitedContractSize` doesn't work for Factory deployments

### ISSUE THREAD

**Issue by kendricktan** [ethereumjs/ethereumjs-vm#811] opened 2020-07-10 01:04 UTC
When `unlimitedContractSize` is true, deploying a **Factory** contract works. However if the Factory contract deploys another contract that exceeds the size limit, `ethereumjs-vm` throws an error.

Minimal reproducable repo: https://github.com/kendricktan/ethereumjs-vm-factory-unlimited
(The files are in `test/example.js`). Run the following to get started
```
yarn install
yarn test
```

Related issue: https://github.com/nomiclabs/buidler/issues/660

**Comment by holgerd77** [comment] 2020-07-13 10:58
@kendricktan thanks for reporting, after having a short look at the related conversations I assume that @alcuadrado is on it?

**Comment by holgerd77** [comment] 2020-07-13 11:58
Some context:

- [Ethers v5 ContractFactory](https://docs.ethers.io/v5/api/contract/contract-factory/)

**Comment by alcuadrado** [comment] 2020-07-13 17:44
Yes, I'm on it. This is probably a bug in how Buidler reports some OOG errors. Let's keep this open until I can confirm this.

**Comment by jochem-brouwer** [comment] 2020-07-15 18:08
Cannot reproduce this in the VM; created a 24577-byte contract with `allowUnlimitedContractSize` set to `true` via both a message-call and via the `CREATE` opcode: both deployed just fine (and they do not deploy if you set `allowUnlimitedContractSize` to `false`). Let me know if I should share the test.

**Comment by jochem-brouwer** [comment] 2020-07-15 18:22
I put the test [here](https://github.com/ethereumjs/ethereumjs-vm/blob/unlimited-contract-size-fix/packages/vm/tests/api/runCall.js#L161)

**Comment by holgerd77** [comment] 2020-09-14 12:35
@alcuadrado any confirmation here?

**Comment by alcuadrado** [comment] 2020-09-14 14:11
We can close this issue. The problem was in buidler evm.

**Closed by alcuadrado** 2020-09-14 14:11 UTC
Labels: package: vm, prio: P3 important, type: bug
